language: node_js
node_js:
  - "4.1.1"

install:
  - npm install --loglevel silent
  - npm install -g firebase-tools --loglevel silent

before_script: ./scripts/ci/clean.sh
script:
  - ./scripts/ci/build.sh
  - ./scripts/ci/test.sh
after_script: ./scripts/ci/clean.sh

notifications:
  email:
    on_success: never